### ISSUE TITLE
Invalid AES key length: 44 bytes

### ISSUE THREAD

**Issue by muke5hy** [damienbeaufils/spring-data-jpa-encryption-example#1]
Hi, 
I'm getting "Invalid AES key length: 44 bytes" exception no matter what I put as Key. Is there any sample key which I can test with. 
Can you provide a way to create the key?

**Comment by damienbeaufils** [comment]
Hello,
AES algorithm allows 128, 192 or 256 bit key length, which is 16, 24 or 32 bytes. So your key should have 16, 24 or 32 characters.
