### ISSUE TITLE
ECB vs CBC

### ISSUE THREAD

**Issue by savicprvoslav** [damienbeaufils/spring-data-jpa-encryption-example#2]
Hi, 
 in the class ```CipherInitializer``` you have used ECB mode. 

If you check the details of this mode you will notice that this is not advised mode to be used and that modes like CBC should be used due to its security. 

[link to check](https://crypto.stackexchange.com/questions/225/should-i-use-ecb-or-cbc-encryption-mode-for-my-block-cipher)

[link to check 2](https://datalocker.com/what-is-the-difference-between-ecb-mode-versus-cbc-mode-aes-encryption/)

Thank you.

**Comment by damienbeaufils** [comment]
@savicprvoslav Thanks for reporting this issue!
